// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUrHEUjdBb-zuTt2pWanklWAaoapsSPoY',
    appId: '1:279728368946:web:9fa64afbfeeb19b50fbb2b',
    messagingSenderId: '279728368946',
    projectId: 'alarmi-9c10a',
    authDomain: 'alarmi-9c10a.firebaseapp.com',
    storageBucket: 'alarmi-9c10a.appspot.com',
    measurementId: 'G-6G01DE6D7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMjZIjqZKOWZsDUyteD72_-nXo-7jMTLI',
    appId: '1:279728368946:android:a50c66369bed21c70fbb2b',
    messagingSenderId: '279728368946',
    projectId: 'alarmi-9c10a',
    storageBucket: 'alarmi-9c10a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwEFUW_wQm9YMM7YKUEfeOnJ_SrRQ9vwQ',
    appId: '1:279728368946:ios:5646eea5e23404080fbb2b',
    messagingSenderId: '279728368946',
    projectId: 'alarmi-9c10a',
    storageBucket: 'alarmi-9c10a.appspot.com',
    iosBundleId: 'com.example.alarmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwEFUW_wQm9YMM7YKUEfeOnJ_SrRQ9vwQ',
    appId: '1:279728368946:ios:4f448960858dd8430fbb2b',
    messagingSenderId: '279728368946',
    projectId: 'alarmi-9c10a',
    storageBucket: 'alarmi-9c10a.appspot.com',
    iosBundleId: 'com.example.alarmi.RunnerTests',
  );
}
